export const initialStartup = {
  name: "NexGen AI Solutions",
  industry: "Штучний інтелект",
  founded: 2023,
  stage: "Серія A",
  status: "Активна",
  markets: ["США", "ЄС", "АТР"],
  offices: ["Київ", "Берлін"],
  employees: 14,
  revenue: 142000,
  expenses: 98000,
  marketShare: 4.2,
  satisfaction: 87,
};

export const competitors = [
  {
    id: 1,
    name: "Cognify Labs",
    sector: "Штучний інтелект",
    size: 120,
    revenue: 3200000,
    markets: "США · ЄС",
    growth: 34,
  },
  {
    id: 2,
    name: "DataMind Co.",
    sector: "Аналітика даних",
    size: 85,
    revenue: 1800000,
    markets: "США",
    growth: 5,
  },
  {
    id: 3,
    name: "Synaptic AG",
    sector: "Машинне навчання",
    size: 210,
    revenue: 8500000,
    markets: "ЄС · АТР",
    growth: 61,
  },
  {
    id: 4,
    name: "Orion Dynamics",
    sector: "SaaS / ШІ",
    size: 44,
    revenue: 620000,
    markets: "США",
    growth: -8,
  },
  {
    id: 5,
    name: "VectorEdge",
    sector: "Глибоке навчання",
    size: 67,
    revenue: 1100000,
    markets: "ЄС · США",
    growth: 22,
  },
  {
    id: 6,
    name: "PulseAI Inc.",
    sector: "НЛП / Автоматизація",
    size: 31,
    revenue: 390000,
    markets: "АТР",
    growth: 2,
  },
];

export const investors = [
  {
    id: 1,
    initials: "AV",
    name: "Apex Ventures",
    focus: "ШІ · Глибокі технології",
    stage: "Серія A–B",
    ticket: "$2M – $15M",
    portfolio: "$340M",
  },
  {
    id: 2,
    initials: "SC",
    name: "Sequoia Capital",
    focus: "SaaS · Споживчий ринок",
    stage: "Seed – Серія C",
    ticket: "$500K – $100M",
    portfolio: "$8.5B",
  },
  {
    id: 3,
    initials: "NF",
    name: "NordFund",
    focus: "Європейські технології",
    stage: "Серія A",
    ticket: "$1M – $8M",
    portfolio: "$210M",
  },
  {
    id: 4,
    initials: "TA",
    name: "TechAlpha Partners",
    focus: "МН · Дані",
    stage: "Pre-A – A",
    ticket: "$750K – $5M",
    portfolio: "$95M",
  },
  {
    id: 5,
    initials: "GV",
    name: "GreenValley VC",
    focus: "Impact · Етика ШІ",
    stage: "Seed – B",
    ticket: "$200K – $12M",
    portfolio: "$180M",
  },
  {
    id: 6,
    initials: "HR",
    name: "HorizonRise Fund",
    focus: "Розширення в АТР",
    stage: "Серія B–C",
    ticket: "$5M – $50M",
    portfolio: "$1.2B",
  },
];